In [167]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [168]:
df=pd.read_csv("quikr_car.csv")
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [169]:
df.shape

(892, 6)

In [170]:
df.size

5352

In [171]:
df.columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='object')

In [172]:
df.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [173]:
backup=df.copy()

In [174]:
df['year']

0      2007
1      2006
2      2018
3      2014
4      2014
       ...
887    zest
888    2018
889    2013
890    2014
891    2014
Name: year, Length: 892, dtype: object

In [175]:
df=df[df['year'].str.isnumeric()]

In [176]:
df['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '2003', '2004', '1995', '2002', '2001'], dtype=object)

In [177]:
df['year']=df['year'].astype(int)

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int32
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int32(1), object(5)
memory usage: 42.8+ KB

In [179]:
df['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '4,35,000', '1,89,700', '3,89,700', '3,60,000',
       '2,95,000', '1,14,990', '10,65,000', '4,70,000', '48,000',
       '1,88,000', '4,65,000', '1,79,999', '21,90,000', '23,90,000',
       '10,75,000', '4,75,000', '10,25,000', '6,15,000', '19,00,000',
       '14,90,000', '15,10,000', '18,50,000', '7,90,000', '17,25,000',
       '12,25,000', '68,000', '9,70,000', '31,00,000', '8,99,000',
       '88,000', '53,000', '5,68,500', '71,000', '5,90,000', '7,95,000',
       '42,000', '1,89,000', '1,62,000', '35,999', '29,00,000', '39,999',
       '50,500', '5,10,000', '8,60,000', '5,00,001'], dtype=object)

In [180]:
df=df[df['Price']!='Ask For Price']

In [181]:
df['Price'].unique()

array(['80,000', '4,25,000', '3,25,000', '5,75,000', '1,75,000',
       '1,90,000', '8,30,000', '2,50,000', '1,82,000', '3,15,000',
       '4,15,000', '3,20,000', '10,00,000', '5,00,000', '3,50,000',
       '1,60,000', '3,10,000', '75,000', '1,00,000', '2,90,000', '95,000',
       '1,80,000', '3,85,000', '1,05,000', '6,50,000', '6,89,999',
       '4,48,000', '5,49,000', '5,01,000', '4,89,999', '2,80,000',
       '3,49,999', '2,84,999', '3,45,000', '4,99,999', '2,35,000',
       '2,49,999', '14,75,000', '3,95,000', '2,20,000', '1,70,000',
       '85,000', '2,00,000', '5,70,000', '1,10,000', '4,48,999',
       '18,91,111', '1,59,500', '3,44,999', '4,49,999', '8,65,000',
       '6,99,000', '3,75,000', '2,24,999', '12,00,000', '1,95,000',
       '3,51,000', '2,40,000', '90,000', '1,55,000', '6,00,000',
       '1,89,500', '2,10,000', '3,90,000', '1,35,000', '16,00,000',
       '7,01,000', '2,65,000', '5,25,000', '3,72,000', '6,35,000',
       '5,50,000', '4,85,000', '3,29,500', '2,51,111', '5,69,999',
       '69,999', '2,99,999', '3,99,999', '4,50,000', '2,70,000',
       '1,58,400', '1,79,000', '1,25,000', '2,99,000', '1,50,000',
       '2,75,000', '2,85,000', '3,40,000', '70,000', '2,89,999',
       '8,49,999', '7,49,999', '2,74,999', '9,84,999', '5,99,999',
       '2,44,999', '4,74,999', '2,45,000', '1,69,500', '3,70,000',
       '1,68,000', '1,45,000', '98,500', '2,09,000', '1,85,000',
       '9,00,000', '6,99,999', '1,99,999', '5,44,999', '1,99,000',
       '5,40,000', '49,000', '7,00,000', '55,000', '8,95,000', '3,55,000',
       '5,65,000', '3,65,000', '40,000', '4,00,000', '3,30,000',
       '5,80,000', '3,79,000', '2,19,000', '5,19,000', '7,30,000',
       '20,00,000', '21,00,000', '14,00,000', '3,11,000', '8,55,000',
       '5,35,000', '1,78,000', '3,00,000', '2,55,000', '5,49,999',
       '3,80,000', '57,000', '4,10,000', '2,25,000', '1,20,000', '59,000',
       '5,99,000', '6,75,000', '72,500', '6,10,000', '2,30,000',
       '5,20,000', '5,24,999', '4,24,999', '6,44,999', '5,84,999',
       '7,99,999', '4,44,999', '6,49,999', '9,44,999', '5,74,999',
       '3,74,999', '1,30,000', '4,01,000', '13,50,000', '1,74,999',
       '2,39,999', '99,999', '3,24,999', '10,74,999', '11,30,000',
       '1,49,000', '7,70,000', '30,000', '3,35,000', '3,99,000', '65,000',
       '1,69,999', '1,65,000', '5,60,000', '9,50,000', '7,15,000',
       '45,000', '9,40,000', '1,55,555', '15,00,000', '4,95,000',
       '8,00,000', '12,99,000', '5,30,000', '14,99,000', '32,000',
       '4,05,000', '7,60,000', '7,50,000', '4,19,000', '1,40,000',
       '15,40,000', '1,23,000', '4,98,000', '4,80,000', '4,88,000',
       '15,25,000', '5,48,900', '7,25,000', '99,000', '52,000',
       '28,00,000', '4,99,000', '3,81,000', '2,78,000', '6,90,000',
       '2,60,000', '90,001', '1,15,000', '15,99,000', '1,59,000',
       '51,999', '2,15,000', '35,000', '11,50,000', '2,69,000', '60,000',
       '4,30,000', '85,00,003', '4,01,919', '4,90,000', '4,24,000',
       '2,05,000', '5,49,900', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [182]:
df['Price']=df['Price'].str.replace(",",'')

In [183]:
df['Price'].unique()

array(['80000', '425000', '325000', '575000', '175000', '190000',
       '830000', '250000', '182000', '315000', '415000', '320000',
       '1000000', '500000', '350000', '160000', '310000', '75000',
       '100000', '290000', '95000', '180000', '385000', '105000',
       '650000', '689999', '448000', '549000', '501000', '489999',
       '280000', '349999', '284999', '345000', '499999', '235000',
       '249999', '1475000', '395000', '220000', '170000', '85000',
       '200000', '570000', '110000', '448999', '1891111', '159500',
       '344999', '449999', '865000', '699000', '375000', '224999',
       '1200000', '195000', '351000', '240000', '90000', '155000',
       '600000', '189500', '210000', '390000', '135000', '1600000',
       '701000', '265000', '525000', '372000', '635000', '550000',
       '485000', '329500', '251111', '569999', '69999', '299999',
       '399999', '450000', '270000', '158400', '179000', '125000',
       '299000', '150000', '275000', '285000', '340000', '70000',
       '289999', '849999', '749999', '274999', '984999', '599999',
       '244999', '474999', '245000', '169500', '370000', '168000',
       '145000', '98500', '209000', '185000', '900000', '699999',
       '199999', '544999', '199000', '540000', '49000', '700000', '55000',
       '895000', '355000', '565000', '365000', '40000', '400000',
       '330000', '580000', '379000', '219000', '519000', '730000',
       '2000000', '2100000', '1400000', '311000', '855000', '535000',
       '178000', '300000', '255000', '549999', '380000', '57000',
       '410000', '225000', '120000', '59000', '599000', '675000', '72500',
       '610000', '230000', '520000', '524999', '424999', '644999',
       '584999', '799999', '444999', '649999', '944999', '574999',
       '374999', '130000', '401000', '1350000', '174999', '239999',
       '99999', '324999', '1074999', '1130000', '149000', '770000',
       '30000', '335000', '399000', '65000', '169999', '165000', '560000',
       '950000', '715000', '45000', '940000', '155555', '1500000',
       '495000', '800000', '1299000', '530000', '1499000', '32000',
       '405000', '760000', '750000', '419000', '140000', '1540000',
       '123000', '498000', '480000', '488000', '1525000', '548900',
       '725000', '99000', '52000', '2800000', '499000', '381000',
       '278000', '690000', '260000', '90001', '115000', '1599000',
       '159000', '51999', '215000', '35000', '1150000', '269000', '60000',
       '430000', '8500003', '401919', '490000', '424000', '205000',
       '549900', '435000', '189700', '389700', '360000', '295000',
       '114990', '1065000', '470000', '48000', '188000', '465000',
       '179999', '2190000', '2390000', '1075000', '475000', '1025000',
       '615000', '1900000', '1490000', '1510000', '1850000', '790000',
       '1725000', '1225000', '68000', '970000', '3100000', '899000',
       '88000', '53000', '568500', '71000', '590000', '795000', '42000',
       '189000', '162000', '35999', '2900000', '39999', '50500', '510000',
       '860000', '500001'], dtype=object)

In [184]:
df.sample()

                     name   company  year   Price  kms_driven fuel_type
473  Mahindra Scorpio S10  Mahindra  2015  900000  97,200 kms    Diesel

In [185]:
df['kms_driven']=df['kms_driven'].str.replace(",","")

In [186]:
df.sample()

,name,company,year,Price,kms_driven,fuel_type
694,Mitsubishi Pajero Sport 2.5 AT,Mitsubishi,2015,1725000,37000 kms,Diesel

In [187]:
df['kms_driven']=df['kms_driven'].str.split().str.get(0)

In [188]:
df['kms_driven'].unique()

array(['45000', '40', '28000', '36000', '41000', '25000', '24530',
       '60000', '30000', '32000', '48660', '4000', '16934', '43000',
       '35550', '39522', '39000', '55000', '72000', '15975', '70000',
       '23452', '35522', '48508', '15487', '82000', '20000', '68000',
       '38000', '27000', '33000', '46000', '16000', '47000', '35000',
       '30874', '15000', '29685', '130000', '19000', '54000', '13000',
       '38200', '22000', '50000', '13500', '3600', '45863', '60500',
       '12500', '18000', '13349', '29000', '44000', '42000', '14000',
       '49000', '36200', '51000', '104000', '33333', '33600', '5600',
       '7500', '26000', '24330', '65480', '200000', '59000', '99000',
       '2800', '21000', '11000', '66000', '3000', '7000', '38500',
       '37200', '43200', '24800', '45872', '40000', '11400', '97200',
       '52000', '31000', '175430', '37000', '65000', '3350', '75000',
       '62000', '73000', '2200', '54870', '34580', '97000', '60', '80200',
       '3200', '0000', '5000', '588', '71200', '175400', '9300', '56758',
       '10000', '56450', '56000', '32700', '9000', '73', '160000',
       '58559', '57000', '170000', '80000', '6821', '23000', '34000',
       '1800', '400000', '48000', '90000', '12000', '69900', '166000',
       '122', '0', '36469', '7800', '24695', '15141', '59910', '100000',
       '4500', '129000', '300', '131000', '111111', '59466', '25500',
       '44005', '2110', '43222', '100200', '65', '140000', '103553',
       '58000', '120000', '49800', '100', '81876', '6020', '55700',
       '18500', '53000', '35500', '22134', '1000', '8500', '87000',
       '6000', '8000', '55800', '56400', '72160', '11500', '133000',
       '2000', '88000', '65422', '117000', '150000', '10750', '6800',
       '9800', '57923', '30201', '6200', '37518', '24652', '383', '95000',
       '3528', '52500', '47900', '52800', '195000', '48008', '48247',
       '9400', '64000', '2137', '10544', '147000', '90001', '48006',
       '74000', '85000', '29500', '39700', '67000', '19336', '60105',
       '45933', '102563', '28600', '41800', '116000', '42590', '7400',
       '54500', '76000', '00', '11523', '38600', '95500', '37458',
       '85960', '12516', '30600', '2550', '62500', '69000', '28400',
       '68485', '3500', '85455', '63000', '1600', '77000', '26500',
       '2875', '13900', '1500', '2450', '1625', '33400', '60123',
       '137495', '91200', '146000', '100800', '2100', '2500', '132000',
       'Petrol'], dtype=object)

In [189]:
df=df[df['kms_driven'].str.isnumeric()]

In [190]:
df['kms_driven'].unique()

array(['45000', '40', '28000', '36000', '41000', '25000', '24530',
       '60000', '30000', '32000', '48660', '4000', '16934', '43000',
       '35550', '39522', '39000', '55000', '72000', '15975', '70000',
       '23452', '35522', '48508', '15487', '82000', '20000', '68000',
       '38000', '27000', '33000', '46000', '16000', '47000', '35000',
       '30874', '15000', '29685', '130000', '19000', '54000', '13000',
       '38200', '22000', '50000', '13500', '3600', '45863', '60500',
       '12500', '18000', '13349', '29000', '44000', '42000', '14000',
       '49000', '36200', '51000', '104000', '33333', '33600', '5600',
       '7500', '26000', '24330', '65480', '200000', '59000', '99000',
       '2800', '21000', '11000', '66000', '3000', '7000', '38500',
       '37200', '43200', '24800', '45872', '40000', '11400', '97200',
       '52000', '31000', '175430', '37000', '65000', '3350', '75000',
       '62000', '73000', '2200', '54870', '34580', '97000', '60', '80200',
       '3200', '0000', '5000', '588', '71200', '175400', '9300', '56758',
       '10000', '56450', '56000', '32700', '9000', '73', '160000',
       '58559', '57000', '170000', '80000', '6821', '23000', '34000',
       '1800', '400000', '48000', '90000', '12000', '69900', '166000',
       '122', '0', '36469', '7800', '24695', '15141', '59910', '100000',
       '4500', '129000', '300', '131000', '111111', '59466', '25500',
       '44005', '2110', '43222', '100200', '65', '140000', '103553',
       '58000', '120000', '49800', '100', '81876', '6020', '55700',
       '18500', '53000', '35500', '22134', '1000', '8500', '87000',
       '6000', '8000', '55800', '56400', '72160', '11500', '133000',
       '2000', '88000', '65422', '117000', '150000', '10750', '6800',
       '9800', '57923', '30201', '6200', '37518', '24652', '383', '95000',
       '3528', '52500', '47900', '52800', '195000', '48008', '48247',
       '9400', '64000', '2137', '10544', '147000', '90001', '48006',
       '74000', '85000', '29500', '39700', '67000', '19336', '60105',
       '45933', '102563', '28600', '41800', '116000', '42590', '7400',
       '54500', '76000', '00', '11523', '38600', '95500', '37458',
       '85960', '12516', '30600', '2550', '62500', '69000', '28400',
       '68485', '3500', '85455', '63000', '1600', '77000', '26500',
       '2875', '13900', '1500', '2450', '1625', '33400', '60123',
       '137495', '91200', '146000', '100800', '2100', '2500', '132000'],
      dtype=object)

In [191]:
df['kms_driven']=df['kms_driven'].astype(int)

In [192]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    object
 4   kms_driven  817 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.3+ KB

In [193]:
df.isnull().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     1
dtype: int64

In [194]:
df=df.dropna()

In [195]:
df['name']=df['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [196]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [197]:
df.reset_index(drop=True)

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [198]:
df['Price']=df['Price'].astype(int)

In [199]:
df.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [200]:
df=df[df['Price']<6e6].reset_index(drop=True)

In [201]:
df.describe()

              year         Price     kms_driven
count   815.000000  8.150000e+02     815.000000
mean   2012.442945  4.017933e+05   46277.096933
std       4.005079  3.815888e+05   34318.459638
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.900000e+05   56879.000000
max    2019.000000  3.100000e+06  400000.000000

In [202]:
df.to_csv("cartransformed data.csv")

# Model

In [203]:
X=df.drop(columns='Price')
Y=df['Price']

In [204]:
X

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [205]:
Y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int32

In [216]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,random_state=302)

In [217]:
ohe=OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [218]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                    remainder='passthrough')

In [219]:
lr=LinearRegression()

In [220]:
pipe=make_pipeline(column_trans,lr)

In [221]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [222]:
y_pred=pipe.predict(X_test)

In [223]:
r2_score(Y_test,y_pred)

0.8991116065992623

In [214]:
# scores=[]
# for i in range(1000):
#     X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.1,random_state=i)
#     lr=LinearRegression()
#     pipe=make_pipeline(column_trans,lr)
#     pipe.fit(X_train,y_train)
#     y_pred=pipe.predict(X_test)
#     scores.append(r2_score(y_test,y_pred))
# np.argmax(scores)

In [225]:
import pickle
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]